steps:
  # reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'northamerica-northeast2-docker.pkg.dev/sleepr-424523/reservations/production'
      '-f'
      'apps/reservations/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'northamerica-northeast2-docker.pkg.dev/sleepr-424523/reservations/production']

  # auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'northamerica-northeast2-docker.pkg.dev/sleepr-424523/auth/production'
      '-f'
      'apps/auth/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'northamerica-northeast2-docker.pkg.dev/sleepr-424523/auth/production']

# notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'northamerica-northeast2-docker.pkg.dev/sleepr-424523/notifications/production'
      '-f'
      'apps/notifications/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'northamerica-northeast2-docker.pkg.dev/sleepr-424523/notifications/production']

  #payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'northamerica-northeast2-docker.pkg.dev/sleepr-424523/payments/production'
      '-f'
      'apps/payments/Dockerfile',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'northamerica-northeast2-docker.pkg.dev/sleepr-424523/payments/production']