services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations # override cmd defined in DockerFile
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth # override cmd defined in DockerFile
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments # override cmd defined in DockerFile
    env_file:
      - ./apps/payments/.env
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications # override cmd defined in DockerFile
    env_file:
      - ./apps/notifications/.env
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway # override cmd defined in DockerFile
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3004:3004'
    depends_on:
      - reservations
  mongo:
    image: mongo